name: Deploy API to Server

on:
  push:
    branches:
      - main # Ganti ke branch yang kamu gunakan

jobs:
  deploy:
    runs-on: self-hosted  # ini pakai runner yang kamu siapkan tadi
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy ke server
        run: |
          # Contoh script deploy sederhana:
          git pull origin main
          npm install